import './styles/globals.css'
import AuthLayout from './layouts/AuthLayout'
import DashboardLayout from './layouts/DashboardLayout'
import SessionProvider from './utils/SessionProvider'
import { getServerSession } from 'next-auth'

export const metadata = {
  title: 'Calisthenics App',
  description: 'Generated by create next app'
}

export default async function RootLayout({ children }) {
  const session = await getServerSession()

  return (
    <SessionProvider session={session}>
      {session ? (
        <DashboardLayout>{children}</DashboardLayout>
      ) : (
        <AuthLayout>{children}</AuthLayout>
      )}
    </SessionProvider>
  )
}
