import AuthLayout from './AuthLayout'
import DashboardLayout from './DashboardLayout'

import './styles/globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Calisthenics App',
  description: 'Generated by create next app'
}
export default function RootLayout({ children }) {
  const isAuthScreen = true

  if (isAuthScreen) {
    return <AuthLayout>{children}</AuthLayout>
  } else {
    return <DashboardLayout>{children}</DashboardLayout>
  }
}
